import React, { createContext, useState, useContext, useCallback } from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import './styles/index.css';
import App from './App';

const TRANSLATIONS = { en: {} };

function addTranslations(lang, strings) {
  TRANSLATIONS[lang] = strings;
}

addTranslations('en', {
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.allTools': 'All Tools',
  'nav.tools.merge': 'Merge PDF',
  'nav.tools.split': 'Split PDF',
  'nav.tools.compress': 'Compress PDF',
  'nav.tools.rotate': 'Rotate PDF',
  'nav.tools.protect': 'Protect PDF',
  'nav.tools.unlock': 'Unlock PDF',
  'nav.tools.addPageNumbers': 'Add Page Numbers',
  'nav.tools.addWatermark': 'Add Watermark',
  'nav.tools.extractText': 'Extract Text',
  'nav.tools.reorderPages': 'Reorder Pages',
  'nav.tools.deletePages': 'Delete Pages',
  'nav.tools.pdfToJpg': 'PDF to JPG',
  'nav.tools.jpgToPdf': 'JPG to PDF',
  'nav.tools.pdfToTxt': 'PDF to TXT',
  'nav.tools.pdfToWord': 'PDF to Word',
  'nav.tools.wordToPdf': 'Word to PDF',
  'nav.tools.pdfToPpt': 'PDF to PPT',
  'nav.tools.pptToPdf': 'PPT to PDF',
  'nav.tools.pdfToExcel': 'PDF to Excel',
  'nav.tools.excelToPdf': 'Excel to PDF',
  'nav.tools.editPdf': 'Edit PDF',
  'nav.tools.signPdf': 'Sign PDF',
  'nav.tools.repairPdf': 'Repair PDF',
  'nav.tools.pdfToPdfa': 'PDF to PDF/A',
  'nav.tools.pdfMetadata': 'PDF Metadata',
  'nav.tools.flattenPdf': 'Flatten PDF',
  'nav.tools.htmlToPdf': 'HTML to PDF',
  'nav.tools.redactPdf': 'Redact PDF',
  'nav.tools.removeAnnotations': 'Remove Annotations',
  'nav.tools.removeWatermark': 'Remove Watermark',
  'nav.tools.comparePdf': 'Compare PDF',
  'nav.dashboard': 'Dashboard',
  'nav.history': 'History',
  'nav.logout': 'Logout',
  'nav.login': 'Login',
  'nav.register': 'Register',
  'nav.language': 'Language',
  'nav.hello': 'Fully online — no download required',
  'hero.title1': 'Your PDFs,',
  'hero.title2': 'Perfected.',
  'hero.desc': 'Doczen is the all-in-one PDF workspace. Merge, split, convert, compress, edit, and sign documents — all in your browser, free and secure.',
  'hero.tryMerge': 'Try Merge PDF',
  'hero.allTools': 'All Tools',
  'tools.header': 'Everything You Need',
  'tools.subtitle': 'From quick edits to full conversions — 31 powerful tools at your fingertips.',
  'tool.mergePdf': 'Merge PDF',
  'tool.mergePdfDesc': 'Combine multiple PDFs into one file instantly.',
  'tool.splitPdf': 'Split PDF',
  'tool.splitPdfDesc': 'Split a PDF into separate documents by pages.',
  'tool.compressPdf': 'Compress PDF',
  'tool.compressPdfDesc': 'Reduce PDF file size without quality loss.',
  'tool.rotatePdf': 'Rotate PDF',
  'tool.rotatePdfDesc': 'Rotate pages in your PDF to any angle.',
  'tool.protectPdf': 'Protect PDF',
  'tool.protectPdfDesc': 'Add a password to secure your PDF files.',
  'tool.unlockPdf': 'Unlock PDF',
  'tool.unlockPdfDesc': 'Remove password protection from PDFs.',
  'tool.addPageNumbers': 'Add Page Numbers',
  'tool.addPageNumbersDesc': 'Insert page numbers into your PDF document.',
  'tool.addWatermark': 'Add Watermark',
  'tool.addWatermarkDesc': 'Add text or image watermarks to PDFs.',
  'tool.extractText': 'Extract Text',
  'tool.extractTextDesc': 'Extract all text content from a PDF file.',
  'tool.reorderPages': 'Reorder Pages',
  'tool.reorderPagesDesc': 'Arrange PDF pages in the order you need.',
  'tool.deletePages': 'Delete Pages',
  'tool.deletePagesDesc': 'Remove unwanted pages from your PDF.',
  'tool.pdfToJpg': 'PDF to JPG',
  'tool.pdfToJpgDesc': 'Convert PDF pages to high-quality JPG images.',
  'tool.jpgToPdf': 'JPG to PDF',
  'tool.jpgToPdfDesc': 'Convert your images into a PDF document.',
  'tool.pdfToTxt': 'PDF to TXT',
  'tool.pdfToTxtDesc': 'Extract text from PDF into a TXT file.',
  'tool.pdfToWord': 'PDF to Word',
  'tool.pdfToWordDesc': 'Convert PDF to editable Word documents.',
  'tool.wordToPdf': 'Word to PDF',
  'tool.wordToPdfDesc': 'Convert Word documents to PDF format.',
  'tool.pdfToPpt': 'PDF to PPT',
  'tool.pdfToPptDesc': 'Turn your PDF into PowerPoint slides.',
  'tool.pptToPdf': 'PPT to PDF',
  'tool.pptToPdfDesc': 'Convert PowerPoint presentations to PDF.',
  'tool.pdfToExcel': 'PDF to Excel',
  'tool.pdfToExcelDesc': 'Extract PDF tables into Excel spreadsheets.',
  'tool.excelToPdf': 'Excel to PDF',
  'tool.excelToPdfDesc': 'Convert Excel spreadsheets to PDF format.',
  'tool.editPdf': 'Edit PDF',
  'tool.editPdfDesc': 'Edit text, images, and pages in your PDF.',
  'tool.signPdf': 'Sign PDF',
  'tool.signPdfDesc': 'Add your digital signature to any document.',
  'tool.repairPdf': 'Repair PDF',
  'tool.repairPdfDesc': 'Fix corrupted or damaged PDF files.',
  'tool.pdfToPdfa': 'PDF to PDF/A',
  'tool.pdfToPdfaDesc': 'Convert PDFs to archival PDF/A format.',
  'tool.pdfMetadata': 'PDF Metadata',
  'tool.pdfMetadataDesc': 'View and edit PDF document properties.',
  'tool.flattenPdf': 'Flatten PDF',
  'tool.flattenPdfDesc': 'Flatten form fields and annotations.',
  'tool.htmlToPdf': 'HTML to PDF',
  'tool.htmlToPdfDesc': 'Convert web content to PDF documents.',
  'tool.redactPdf': 'Redact PDF',
  'tool.redactPdfDesc': 'Permanently remove sensitive information.',
  'tool.removeAnnotations': 'Remove Annotations',
  'tool.removeAnnotationsDesc': 'Clean up comments and markup.',
  'tool.removeWatermark': 'Remove Watermark',
  'tool.removeWatermarkDesc': 'Remove watermarks from PDF documents.',
  'tool.comparePdf': 'Compare PDF',
  'tool.comparePdfDesc': 'Compare two PDF files side by side.',
  'tool.tryNow': 'Try now',
  'faq.header': 'Frequently Asked Questions',
  'faq.q1': 'Is Doczen free to use?',
  'faq.a1': 'Yes! Doczen is completely free to use. All PDF tools are available with no hidden charges.',
  'faq.q2': 'Are my files secure?',
  'faq.a2': 'Absolutely. All files are encrypted during upload and automatically deleted from our servers after 24 hours. We never share your data.',
  'faq.q3': 'What file sizes are supported?',
  'faq.a3': 'You can upload files up to 50 MB per document.',
  'faq.q4': 'How long does processing take?',
  'faq.a4': 'Most operations complete within seconds. Complex conversions may take a bit longer, but we optimize everything for speed.',
  'faq.q5': 'Is there a daily limit?',
  'faq.a5': 'No registration needed — guests can process up to 10 files per hour. Create a free account for higher limits and history tracking.',
  'faq.q6': 'What happens to my data?',
  'faq.a6': 'All uploaded files are automatically deleted from our servers within 24 hours. You can also manually delete your history at any time.',
  'cta.header': 'Ready to Simplify Your PDF Workflow?',
  'cta.desc': 'Start for free — no credit card needed, no sign up required.',
  'cta.start': 'Start Using Tools',
  'cta.compress': 'Compress a PDF',
  'footer.tagline': 'The simplest way to edit, convert, and manage your PDF documents online. Fast, secure, and free.',
  'footer.quickLinks': 'Quick Links',
  'footer.moreTools': 'More Tools',
  'footer.company': 'Company',
  'footer.about': 'About',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.copyright': 'All rights reserved.',
  'footer.builtWith': 'Built with ❤️ for PDFs',
  'about.title': 'About Doczen',
  'about.p1': 'Doczen is a free, powerful online PDF editor designed to make document management simple and accessible for everyone. Whether you need to merge, split, compress, convert, or edit PDFs, Doczen provides all the tools you need right in your browser — no downloads, no installations.',
  'about.p2': 'Our mission is to democratize PDF editing by offering a comprehensive suite of tools that are completely free to use. We believe that essential document management should not require expensive software subscriptions.',
  'about.p3': 'Every tool on Doczen is built with modern web technologies to ensure fast, secure, and reliable processing. Your privacy is our priority — all files are encrypted during upload and automatically deleted from our servers within 24 hours.',
  'about.whyTitle': 'Why Doczen?',
  'about.why1': '100% Free — No hidden charges, no credit card required',
  'about.why2': '30+ Tools — From merging to converting, we\'ve got you covered',
  'about.why3': 'Secure — Encrypted uploads and automatic file deletion',
  'about.why4': 'Fast — Optimized processing for quick results',
  'about.why5': 'No Registration — Start using tools immediately',
  'privacy.title': 'Privacy Policy',
  'privacy.lastUpdated': 'Last updated: January 2025',
  'privacy.p1': 'Doczen ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service.',
  'privacy.collectTitle': 'Information We Collect',
  'privacy.collect1': 'Files You Upload: PDFs and documents you upload for processing are temporarily stored on our servers.',
  'privacy.collect2': 'Account Information: If you create an account, we collect your name and email address.',
  'privacy.collect3': 'Usage Data: Anonymous usage statistics to improve our service.',
  'privacy.filesTitle': 'How We Handle Your Files',
  'privacy.files1': 'All uploaded files are encrypted during transmission and at rest.',
  'privacy.files2': 'Files are automatically and permanently deleted from our servers within 24 hours.',
  'privacy.files3': 'We do not access, view, or share your uploaded documents.',
  'privacy.files4': 'Processed files are available for download for a limited time before automatic deletion.',
  'privacy.cookiesTitle': 'Cookies',
  'privacy.cookiesDesc': 'We use essential cookies for authentication and service functionality. We do not use tracking cookies for advertising purposes.',
  'privacy.thirdPartyTitle': 'Third-Party Services',
  'privacy.thirdPartyDesc': 'We do not sell, trade, or transfer your information to third parties. We may share anonymized data with service providers who assist us in operating our website and improving our service.',
  'privacy.contactTitle': 'Contact',
  'privacy.contactDesc': 'If you have questions about this Privacy Policy, please contact us at support@doczen.com.',
  'terms.title': 'Terms of Service',
  'terms.lastUpdated': 'Last updated: January 2025',
  'terms.p1': 'By using Doczen, you agree to these Terms of Service. If you do not agree, please do not use our service.',
  'terms.useTitle': 'Use of Service',
  'terms.use1': 'Not upload malicious files or content that violates any law.',
  'terms.use2': 'Not attempt to disrupt or overload our servers.',
  'terms.use3': 'Not use the service for any unlawful purpose.',
  'terms.use4': 'Comply with all applicable laws and regulations.',
  'terms.ipTitle': 'Intellectual Property',
  'terms.ipDesc': 'You retain all rights to your uploaded documents. Doczen claims no ownership over your files. Our software, brand, and website content are protected by applicable intellectual property laws.',
  'terms.limitationTitle': 'Limitation of Liability',
  'terms.limitationDesc': 'Doczen is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service. We do not guarantee that the service will be uninterrupted or error-free.',
  'terms.storageTitle': 'File Storage',
  'terms.storageDesc': 'Uploaded files are automatically deleted within 24 hours. We recommend downloading your processed files promptly. We are not responsible for data loss.',
  'terms.changesTitle': 'Changes to Terms',
  'terms.changesDesc': 'We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.',
  'login.title': 'Welcome Back',
  'login.subtitle': 'Sign in to your Doczen account',
  'login.email': 'Email Address',
  'login.emailPlaceholder': 'you@example.com',
  'login.password': 'Password',
  'login.passwordPlaceholder': 'Enter your password',
  'login.signIn': 'Sign In',
  'login.noAccount': 'Don\'t have an account?',
  'login.createOne': 'Create one',
  'login.error.required': 'Please fill in all fields.',
  'login.error.invalid': 'Invalid email or password.',
  'register.title': 'Create Your Account',
  'register.subtitle': 'Start using Doczen in seconds',
  'register.name': 'Full Name',
  'register.namePlaceholder': 'John Doe',
  'register.email': 'Email Address',
  'register.emailPlaceholder': 'you@example.com',
  'register.password': 'Password',
  'register.passwordPlaceholder': 'At least 6 characters',
  'register.confirmPassword': 'Confirm Password',
  'register.confirmPasswordPlaceholder': 'Repeat your password',
  'register.createAccount': 'Create Account',
  'register.hasAccount': 'Already have an account?',
  'register.signIn': 'Sign in',
  'register.error.required': 'Please fill in all fields.',
  'register.error.passwordLength': 'Password must be at least 6 characters.',
  'register.error.passwordMatch': 'Passwords do not match.',
  'register.error.failed': 'Registration failed. Please try again.',
  'dashboard.welcome': 'Welcome back',
  'dashboard.subtitle': 'Here\'s what\'s happening with your documents today.',
  'dashboard.filesToday': 'Files Today',
  'dashboard.quickActions': 'Quick Actions',
  'dashboard.recentActivity': 'Recent Activity',
  'dashboard.viewAll': 'View All',
  'dashboard.noActivity': 'No activity yet. Start by using one of the tools above!',
  'dashboard.quick.mergePdf': 'Merge PDF',
  'dashboard.quick.splitPdf': 'Split PDF',
  'dashboard.quick.compress': 'Compress',
  'dashboard.quick.rotate': 'Rotate',
  'dashboard.quick.jpgToPdf': 'JPG to PDF',
  'dashboard.quick.editPdf': 'Edit PDF',
  'history.title': 'History',
  'history.subtitle': 'View all your past PDF operations.',
  'history.clearAll': 'Clear All',
  'history.clearing': 'Clearing...',
  'history.confirmClear': 'Are you sure you want to clear all history?',
  'history.noHistory': 'No history yet.',
  'history.noHistoryDesc': 'Your processed files will appear here.',
  'history.action': 'Action',
  'history.file': 'File',
  'history.date': 'Date',
  'history.status': 'Status',
  'history.size': 'Size',
  'history.previous': 'Previous',
  'history.next': 'Next',
  'history.deleteTitle': 'Delete entry',
  'history.untitled': 'Untitled',
  'upload.label': 'Upload your files',
  'upload.dragActive': 'Release to upload',
  'upload.filesSelected': 'Files selected — drop more or click to change',
  'upload.dropActive': 'Great, drop them here!',
  'upload.tapToAdd': 'Tap to add more files',
  'upload.dragMultiple': 'Drag & drop up to {maxFiles} files here, or click to browse',
  'upload.dragSingle': 'Drag & drop a file here, or click to browse',
  'upload.uploading': 'Uploading...',
  'upload.error.invalidType': 'Invalid file type. Please upload a valid file.',
  'upload.error.fileTooLarge': 'File too large. Maximum size is 50MB.',
  'upload.error.singleFile': 'Only one file can be uploaded at a time.',
  'upload.error.maxFiles': 'Maximum of {maxFiles} files allowed.',
  'upload.removeFile': 'Remove file',
  'result.action': 'Your file was successfully {action}.',
  'result.file': 'File',
  'result.size': 'Size',
  'result.compression': 'Compression',
  'result.original': 'Original',
  'result.processAnother': 'Process Another',
  'result.downloadAgain': 'Download Again',
  'result.smaller': '{pct}% smaller',
  'tool.uploadPdf': 'Upload PDF',
  'tool.uploadPdfs': 'Upload PDFs',
  'tool.uploadPdfFile': 'Upload PDF file',
  'tool.selectPdf': 'Please select a PDF file.',
  'tool.selectPdfs': 'Please select at least 2 PDF files to merge.',
  'tool.mergePdf': 'Merge PDFs',
  'tool.merging': 'Merging PDFs...',
  'tool.splitPdf': 'Split PDF',
  'tool.splitting': 'Splitting PDF...',
  'tool.compressPdf': 'Compress PDF',
  'tool.compressing': 'Compressing PDF...',
  'tool.rotatePdf': 'Rotate PDF',
  'tool.rotating': 'Rotating PDF...',
  'tool.protectPdf': 'Protect PDF',
  'tool.protecting': 'Protecting PDF...',
  'tool.unlockPdf': 'Unlock PDF',
  'tool.unlocking': 'Unlocking PDF...',
  'tool.addPageNumbers': 'Add Page Numbers',
  'tool.addingPageNumbers': 'Adding page numbers...',
  'tool.addWatermark': 'Add Watermark',
  'tool.addingWatermark': 'Adding watermark...',
  'tool.extractText': 'Extract Text',
  'tool.extracting': 'Extracting text...',
  'tool.reorderPages': 'Reorder Pages',
  'tool.reordering': 'Reordering pages...',
  'tool.deletePages': 'Delete Pages',
  'tool.deleting': 'Deleting pages...',
  'tool.pdfToJpg': 'PDF to JPG',
  'tool.convertingToJpg': 'Converting to JPG...',
  'tool.jpgToPdf': 'JPG to PDF',
  'tool.convertingToPdf': 'Convert to PDF',
  'tool.pdfToTxt': 'PDF to TXT',
  'tool.extractingText': 'Extract Text',
  'tool.pdfToWord': 'PDF to Word',
  'tool.convertingToWord': 'Convert to Word',
  'tool.wordToPdf': 'Word to PDF',
  'tool.pdfToPpt': 'PDF to PPT',
  'tool.convertingToPpt': 'Convert to PPT',
  'tool.pptToPdf': 'PPT to PDF',
  'tool.pdfToExcel': 'PDF to Excel',
  'tool.convertingToExcel': 'Convert to Excel',
  'tool.excelToPdf': 'Excel to PDF',
  'tool.editPdf': 'Edit PDF',
  'tool.signPdf': 'Sign PDF',
  'tool.repairPdf': 'Repair PDF',
  'tool.repairing': 'Repairing PDF...',
  'tool.pdfToPdfa': 'PDF to PDF/A',
  'tool.convertingToPdfa': 'Converting to PDF/A...',
  'tool.pdfMetadata': 'PDF Metadata',
  'tool.flattenPdf': 'Flatten PDF',
  'tool.flattening': 'Flattening PDF...',
  'tool.htmlToPdf': 'HTML to PDF',
  'tool.convertingHtml': 'Converting to PDF...',
  'tool.redactPdf': 'Redact PDF',
  'tool.redacting': 'Redacting PDF...',
  'tool.removeAnnotations': 'Remove Annotations',
  'tool.removingAnnotations': 'Removing Annotations...',
  'tool.removeWatermark': 'Remove Watermark',
  'tool.removingWatermark': 'Removing Watermark...',
  'tool.comparePdf': 'Compare PDFs',
  'tool.comparing': 'Comparing PDFs...',
  'tool.success': 'File converted successfully. Download started automatically. You can download it again below.',
  'tool.downloadAgain': 'Download Again',
  'tool.uploadPdfDesc': 'Upload a PDF to view its metadata including title, author, subject, keywords, page count, and page sizes.',
  'tool.enterPassword': 'Enter Password',
  'tool.currentPassword': 'Current Password',
  'tool.enterPdfPassword': 'Enter the PDF password',
  'tool.setPassword': 'Set Password',
  'tool.password': 'Password',
  'tool.confirmPassword': 'Confirm Password',
  'tool.enterStrongPassword': 'Enter a strong password',
  'tool.reEnterPassword': 'Re-enter the password',
  'tool.qualitySettings': 'Quality Settings',
  'tool.compressionQuality': 'Compression Quality',
  'tool.lowSmaller': 'Low (smaller file)',
  'tool.highBetter': 'High (better quality)',
  'tool.rotationAngle': 'Rotation Angle',
  'tool.pageNumberSettings': 'Page Number Settings',
  'tool.startNumber': 'Start Number',
  'tool.fontSize': 'Font Size',
  'tool.position': 'Position',
  'tool.bottomCenter': 'Bottom Center',
  'tool.topCenter': 'Top Center',
  'tool.watermarkText': 'Watermark Text',
  'tool.enterWatermarkText': 'Enter the watermark text',
  'tool.watermarkExample': 'e.g. CONFIDENTIAL, DRAFT, SAMPLE',
  'tool.watermarkDesc': 'The watermark will be applied diagonally across every page.',
  'tool.pageOrder': 'Page Order',
  'tool.enterPageOrder': 'Enter the new page order',
  'tool.pageOrderExample': 'e.g. 3, 1, 2, 5, 4',
  'tool.pageOrderHint': 'Enter page numbers separated by commas in the desired order. Example:',
  'tool.pagesToDelete': 'Pages to Delete',
  'tool.enterPagesToDelete': 'Enter the page numbers to delete',
  'tool.pagesToDeleteExample': 'e.g. 1, 3, 5',
  'tool.pagesToDeleteHint': 'Enter page numbers separated by commas. Example:',
  'tool.pagesToDeleteHint2': 'will delete pages 2, 4, and 6.',
  'tool.termsToRedact': 'Terms to Redact',
  'tool.enterTermsToRedact': 'Enter words or phrases to redact (one per line)',
  'tool.redactExample': 'confidential',
  'tool.redactHint': 'Each term will be permanently blacked out wherever it appears in the document. This action cannot be undone, so please make a backup of your original PDF.',
  'tool.extractedText': 'Extracted Text',
  'tool.copyToClipboard': 'Copy to Clipboard',
  'tool.content': 'Content',
  'tool.enterHtml': 'Enter HTML or plain text',
  'tool.documentSettings': 'Document Settings',
  'tool.documentTitle': 'Document Title',
  'tool.documentInfo': 'Document Information (Optional)',
  'tool.title': 'Title',
  'tool.author': 'Author',
  'tool.subject': 'Subject',
  'tool.keywords': 'Keywords',
  'tool.readMetadata': 'Read Metadata',
  'tool.writeMetadata': 'Write Metadata',
  'tool.readingMetadata': 'Reading Metadata...',
  'tool.updatingMetadata': 'Updating Metadata...',
  'tool.updateMetadata': 'Update Metadata',
  'tool.docMetadata': 'Document Metadata',
  'tool.pageCount': 'Page Count',
  'tool.pageSizes': 'Page Sizes',
  'tool.aboutRepair': 'About PDF Repair',
  'tool.repairDesc': 'This tool attempts to repair corrupted or damaged PDF files. It can fix common issues such as truncated files, cross-reference errors, and structural problems. Upload your damaged PDF and we will try to recover as much content as possible.',
  'tool.aboutFlatten': 'About Flattening',
  'tool.flattenDesc': 'Flattening a PDF merges all layers, annotations, and form fields into a single static layer. This makes the content permanent and non-editable. Use this tool to finalize documents before sharing or publishing, ensuring that form inputs, comments, and markups are locked in place.',
  'tool.aboutAnnotations': 'About This Tool',
  'tool.annotationsDesc': 'This tool removes all annotations from your PDF, including comments, highlights, sticky notes, text boxes, and other markup. The document content itself remains untouched. Use this to clean up reviewed documents before final distribution.',
  'tool.watermarkRemoval': 'About Watermark Removal',
  'tool.watermarkRemovalDesc': 'This tool uses multiple strategies to detect and remove watermarks from your PDF documents. It scans for structured watermark artifacts, recurring overlay objects, and text-based watermarks. Results may vary depending on how the watermark was embedded. Flattened or scanned watermarks cannot always be automatically removed.',
  'tool.firstPdf': 'First PDF',
  'tool.secondPdf': 'Second PDF',
  'tool.uploadFirstPdf': 'Upload first PDF',
  'tool.uploadSecondPdf': 'Upload second PDF',
  'tool.selectBothPdfs': 'Please select both PDF files to compare.',
  'tool.comparisonResults': 'Comparison Results',
  'tool.pageCountFile1': 'Page Count (File 1)',
  'tool.pageCountFile2': 'Page Count (File 2)',
  'tool.fileSize': 'File Size',
  'tool.identical': 'Identical',
  'tool.differencesFound': 'Differences Found',
  'tool.differences': 'Differences:',
  'tool.compareAnother': 'Compare Another',
  'tool.yes': 'Yes',
  'tool.no': 'No',
  'tool.watermarkTextOptional': 'Watermark Text',
  'tool.watermarkOptional': '(optional)',
  'tool.watermarkHelp': 'Known watermark text helps detection',
  'tool.mode': 'Mode',
  'tool.modeAuto': 'Auto',
  'tool.modeAutoDesc': 'Try all removal strategies',
  'tool.modeText': 'Text',
  'tool.modeTextDesc': 'Target text-based watermarks only',
  'tool.watermarkRemoved': 'Watermark Removed',
  'tool.watermarkRemovedDesc': 'The watermark has been successfully removed from your PDF.',
  'tool.couldNotRemove': 'Could Not Auto-Remove',
  'tool.couldNotRemoveDesc': 'This watermark appears to be flattened or embedded in the page content and cannot be automatically removed.',
  'tool.signatureText': 'Signature Text',
  'tool.typeSignature': 'Type your signature...',
  'tool.textToAdd': 'Text to add (first page)',
  'tool.enterTextToAdd': 'Enter text to add to the PDF',
  'tool.editPdf': 'Edit PDF',
  'tool.convertToPdf': 'Convert to PDF',
  'tool.convertToWord': 'Convert to Word',
  'tool.convertToJpg': 'Convert to JPG',
  'tool.convertToPpt': 'Convert to PPT',
  'tool.convertToExcel': 'Convert to Excel',
  'tool.converted': 'converted',
  'tool.merged': 'merged',
  'tool.split': 'split',
  'tool.compressed': 'compressed',
  'tool.rotated': 'rotated',
  'tool.protected': 'protected with password',
  'tool.unlocked': 'unlocked',
  'tool.numbered': 'numbered',
  'tool.watermarked': 'watermarked',
  'tool.extracted': 'extracted',
  'tool.reordered': 'reordered',
  'tool.cleaned': 'cleaned',
  'tool.edited': 'edited',
  'tool.signed': 'signed',
  'tool.repaired': 'repaired',
  'tool.flattened': 'flattened',
  'tool.redacted': 'redacted',
  'tool.annotationsRemoved': 'annotations removed',
  'tool.watermarkRemovedResult': 'watermark removed',
  'tool.convertedToPdfa': 'converted to PDF/A',
  'tool.convertedToPdf': 'converted to PDF',
  'tool.selectPdfRotate': 'Please select a PDF file to rotate.',
  'tool.selectPdfProtect': 'Please select a PDF file to protect.',
  'tool.selectPdfUnlock': 'Please select a PDF file to unlock.',
  'tool.selectPdfRepair': 'Please select a PDF file to repair.',
  'tool.selectPdfFlatten': 'Please select a PDF file to flatten.',
  'tool.selectPdfRedact': 'Please select a PDF file to redact.',
  'tool.selectPdfRemoveWatermark': 'Please select a PDF file to remove watermark from.',
  'tool.selectPdfCompare': 'Please select a PDF file to compare.',
  'tool.enterPasswordError': 'Please enter a password.',
  'tool.passwordMinLength': 'Password must be at least 4 characters long.',
  'tool.passwordDoNotMatch': 'Passwords do not match.',
  'tool.enterPdfPasswordError': 'Please enter the PDF password.',
  'tool.enterWatermarkTextError': 'Please enter watermark text.',
  'tool.enterPageOrderError': 'Please enter the desired page order.',
  'tool.enterValidPageNumbers': 'Please enter valid page numbers (positive integers separated by commas).',
  'tool.enterPagesToDeleteError': 'Please enter the pages to delete.',
  'tool.enterAtLeastOneTerm': 'Please enter at least one term to redact.',
  'tool.enterContentToConvert': 'Please enter HTML or text content to convert.',
  'tool.startNumberError': 'Start number must be at least 1.',
  'tool.fontSizeError': 'Font size must be between 6 and 72.',
  'tool.selectPdfError': 'Please select a PDF file.',
  'tool.enterSignatureText': 'Please type or enter signature text.',
  'tool.genericError': 'Something went wrong.',
  'tool.compressError': 'Failed to compress PDF. Please try again.',
  'tool.mergeError': 'Failed to merge PDFs. Please try again.',
  'tool.splitError': 'Failed to split PDF. Please try again.',
  'tool.rotateError': 'Failed to rotate PDF. Please try again.',
  'tool.unlockError': 'Failed to unlock PDF. Please check your password and try again.',
  'tool.repairError': 'Failed to repair PDF. Please try again.',
  'tool.flattenError': 'Failed to flatten PDF. Please try again.',
  'tool.redactError': 'Failed to redact PDF. Please try again.',
  'tool.annotationsError': 'Failed to remove annotations. Please try again.',
  'tool.watermarkRemoveError': 'Failed to remove watermark. Please try again.',
  'tool.compareError': 'Failed to compare PDFs. Please try again.',
  'tool.metadataReadError': 'Failed to read metadata. Please try again.',
  'tool.metadataWriteError': 'Failed to write metadata. Please try again.',
  'tool.convertError': 'Conversion failed. Please try again.',
  'tool.editError': 'Failed to edit PDF.',
  'tool.signError': 'Failed to sign PDF.',
  'tool.addPageNumbersError': 'Failed to add page numbers. Please try again.',
  'tool.addWatermarkError': 'Failed to add watermark. Please try again.',
  'tool.extractTextError': 'Failed to extract text. Please try again.',
  'tool.reorderError': 'Failed to reorder pages. Please try again.',
  'tool.deletePagesError': 'Failed to delete pages. Please try again.',
  'tool.pdfToPdfaError': 'Failed to convert to PDF/A. Please try again.',
  'tool.toast.merged': 'PDFs merged successfully!',
  'tool.toast.compressed': 'PDF compressed successfully!',
  'tool.seo.defaultTitle': 'Free Online PDF Editor - Merge, Split, Compress & Convert PDFs',
  'tool.seo.defaultDesc': 'Doczen is a free online PDF editor. Merge PDFs, split PDFs, compress PDF files, convert PDF to Word, JPG, PPT, Excel and more. No registration required for basic tools.',
  'tool.seo.defaultKeywords': 'free PDF editor, online PDF tool, merge PDF online, split PDF online, compress PDF, PDF converter, PDF to Word, PDF to JPG, Doczen',
  'tool.seo.loginTitle': 'Login - Doczen PDF Editor',
  'tool.seo.loginDesc': 'Sign in to your Doczen account to access all PDF tools, manage your files, and view your processing history.',
  'tool.seo.loginKeywords': 'login, sign in, Doczen account, PDF editor login',
  'tool.seo.registerTitle': 'Create Free Account - Doczen PDF Editor',
  'tool.seo.registerDesc': 'Create your free Doczen account and get access to all PDF editing tools. Merge, split, compress and convert PDFs online.',
  'tool.seo.registerKeywords': 'register, sign up, create account, free PDF editor, Doczen registration',
  'tool.seo.dashboardTitle': 'Dashboard - Doczen PDF Editor',
  'tool.seo.dashboardDesc': 'Your Doczen dashboard. View usage stats, recent activity, and quick access to all PDF tools.',
  'tool.seo.dashboardKeywords': 'dashboard, PDF tools, Doczen account, file management',
  'tool.seo.historyTitle': 'History - Doczen PDF Editor',
  'tool.seo.historyDesc': 'View your PDF processing history on Doczen. Download previously processed files and track your usage.',
  'tool.seo.historyKeywords': 'PDF history, document history, processed files, Doczen history',
  'tool.status.completed': 'completed',
  'tool.status.failed': 'failed',
  'tool.status.pending': 'pending',
  'tool.mergeDesc': 'Combine multiple PDF files into a single document',
  'tool.splitDesc': 'Extract individual pages from a PDF into separate files',
  'tool.compressDesc': 'Reduce the file size of your PDF without losing quality',
  'tool.rotateDesc': 'Rotate individual pages or entire PDF documents',
  'tool.protectDesc': 'Add password protection to your PDF documents',
  'tool.unlockDesc': 'Remove password protection from your PDF documents',
  'tool.addPageNumbersDesc2': 'Insert page numbers into your PDF document',
  'tool.addWatermarkDesc2': 'Add a text watermark to every page of your PDF',
  'tool.extractTextDesc2': 'Extract all text content from a PDF document',
  'tool.reorderDesc': 'Rearrange the order of pages in your PDF document',
  'tool.deleteDesc': 'Remove specific pages from your PDF document',
  'tool.pdfToJpgDesc2': 'Convert each PDF page into a high-quality JPG image.',
  'tool.jpgToPdfDesc2': 'Combine multiple JPG images into a single PDF document.',
  'tool.pdfToTxtDesc2': 'Extract all text content from your PDF file.',
  'tool.pdfToWordDesc2': 'Convert your PDF files into editable Word documents.',
  'tool.wordToPdfDesc2': 'Convert your Word documents into high-quality PDF files.',
  'tool.pdfToPptDesc2': 'Turn your PDF slides into editable PowerPoint presentations.',
  'tool.pptToPdfDesc2': 'Convert your PowerPoint slides into PDF documents.',
  'tool.pdfToExcelDesc2': 'Convert your PDF data into editable Excel spreadsheets.',
  'tool.excelToPdfDesc2': 'Convert your Excel spreadsheets into PDF format.',
  'tool.editDesc': 'Add annotations, highlights, shapes, and text to your PDF documents.',
  'tool.signDesc': 'Add your signature to PDF documents quickly and securely.',
  'tool.repairDesc2': 'Fix corrupted or damaged PDF files and recover your documents',
  'tool.pdfToPdfaDesc2': 'Convert your PDF to PDF/A format for long-term archiving',
  'tool.metadataDesc': 'View and edit PDF document properties',
  'tool.flattenDesc2': 'Flatten form fields, annotations, and layers in your PDF',
  'tool.htmlToPdfDesc2': 'Convert HTML and text content into a PDF document',
  'tool.redactDesc2': 'Permanently remove sensitive information from your PDF',
  'tool.removeAnnotationsDesc2': 'Remove comments, highlights, and markup from your PDF',
  'tool.removeWatermarkDesc2': 'Remove text and image watermarks from your PDF documents',
  'tool.compareDesc': 'Compare two PDF files and find differences',
  'tool.options': 'Options',
  'tool.cleanedDesc': 'Your cleaned PDF is ready. Download started automatically.',
});

addTranslations('hi', {
  'nav.home': 'होम',
  'nav.about': 'हमारे बारे में',
  'nav.allTools': 'सभी उपकरण',
  'nav.tools.merge': 'PDF मर्ज करें',
  'nav.tools.split': 'PDF विभाजित करें',
  'nav.tools.compress': 'PDF संपीड़ित करें',
  'nav.tools.rotate': 'PDF घुमाएँ',
  'nav.tools.protect': 'PDF सुरक्षित करें',
  'nav.tools.unlock': 'PDF अनलॉक करें',
  'nav.tools.addPageNumbers': 'पृष्ठ संख्या जोड़ें',
  'nav.tools.addWatermark': 'वॉटरमार्क जोड़ें',
  'nav.tools.extractText': 'टेक्स्ट निकालें',
  'nav.tools.reorderPages': 'पृष्ठ पुनर्व्यवस्थित करें',
  'nav.tools.deletePages': 'पृष्ठ हटाएं',
  'nav.tools.pdfToJpg': 'PDF से JPG',
  'nav.tools.jpgToPdf': 'JPG से PDF',
  'nav.tools.pdfToTxt': 'PDF से TXT',
  'nav.tools.pdfToWord': 'PDF से Word',
  'nav.tools.wordToPdf': 'Word से PDF',
  'nav.tools.pdfToPpt': 'PDF से PPT',
  'nav.tools.pptToPdf': 'PPT से PDF',
  'nav.tools.pdfToExcel': 'PDF से Excel',
  'nav.tools.excelToPdf': 'Excel से PDF',
  'nav.tools.editPdf': 'PDF संपादित करें',
  'nav.tools.signPdf': 'PDF पर हस्ताक्षर करें',
  'nav.tools.repairPdf': 'PDF मरम्मत करें',
  'nav.tools.pdfToPdfa': 'PDF से PDF/A',
  'nav.tools.pdfMetadata': 'PDF मेटाडेटा',
  'nav.tools.flattenPdf': 'PDF फ्लैट करें',
  'nav.tools.htmlToPdf': 'HTML से PDF',
  'nav.tools.redactPdf': 'PDF रिडैक्ट करें',
  'nav.tools.removeAnnotations': 'एनोटेशन हटाएं',
  'nav.tools.removeWatermark': 'वॉटरमार्क हटाएं',
  'nav.tools.comparePdf': 'PDF तुलना करें',
  'nav.dashboard': 'डैशबोर्ड',
  'nav.history': 'इतिहास',
  'nav.logout': 'लॉग आउट',
  'nav.login': 'लॉग इन',
  'nav.register': 'पंजीकरण',
  'nav.language': 'भाषा',
  'hero.title1': 'आपके PDF,',
  'hero.title2': 'परफेक्ट बने।',
  'hero.desc': 'Doczen एक ऑल-इन-वन PDF वर्कस्पेस है। मर्ज करें, विभाजित करें, कन्वर्ट करें, संपीड़ित करें, संपादित करें और दस्तावेज़ों पर हस्ताक्षर करें — सब आपके ब्राउज़र में, मुफ्त और सुरक्षित।',
  'hero.tryMerge': 'मर्ज PDF आज़माएं',
  'hero.allTools': 'सभी उपकरण',
  'tools.header': 'वह सब कुछ जो आपको चाहिए',
  'tools.subtitle': 'त्वरित संपादन से लेकर पूर्ण रूपांतरण तक — 31 शक्तिशाली उपकरण आपकी उंगलियों पर।',
  'tool.mergePdf': 'PDF मर्ज करें',
  'tool.mergePdfDesc': 'एकाधिक PDF को तुरंत एक फ़ाइल में मर्ज करें।',
  'tool.splitPdf': 'PDF विभाजित करें',
  'tool.splitPdfDesc': 'PDF को पृष्ठों के अनुसार अलग-अलग दस्तावेज़ों में विभाजित करें।',
  'tool.compressPdf': 'PDF संपीड़ित करें',
  'tool.compressPdfDesc': 'गुणवत्ता खोए बिना PDF फ़ाइल का आकार कम करें।',
  'tool.rotatePdf': 'PDF घुमाएँ',
  'tool.rotatePdfDesc': 'अपने PDF में पृष्ठों को किसी भी कोण पर घुमाएँ।',
  'tool.protectPdf': 'PDF सुरक्षित करें',
  'tool.protectPdfDesc': 'अपनी PDF फ़ाइलों को सुरक्षित करने के लिए पासवर्ड जोड़ें।',
  'tool.unlockPdf': 'PDF अनलॉक करें',
  'tool.unlockPdfDesc': 'PDF से पासवर्ड सुरक्षा हटाएं।',
  'tool.addPageNumbers': 'पृष्ठ संख्या जोड़ें',
  'tool.addPageNumbersDesc': 'अपने PDF दस्तावेज़ में पृष्ठ संख्या जोड़ें।',
  'tool.addWatermark': 'वॉटरमार्क जोड़ें',
  'tool.addWatermarkDesc': 'PDF में टेक्स्ट या इमेज वॉटरमार्क जोड़ें।',
  'tool.extractText': 'टेक्स्ट निकालें',
  'tool.extractTextDesc': 'PDF फ़ाइल से सभी टेक्स्ट सामग्री निकालें।',
  'tool.reorderPages': 'पृष्ठ पुनर्व्यवस्थित करें',
  'tool.reorderPagesDesc': 'PDF पृष्ठों को अपनी आवश्यकता के क्रम में व्यवस्थित करें।',
  'tool.deletePages': 'पृष्ठ हटाएं',
  'tool.deletePagesDesc': 'अपने PDF से अनावश्यक पृष्ठ हटाएं।',
  'tool.pdfToJpg': 'PDF से JPG',
  'tool.pdfToJpgDesc': 'PDF पृष्ठों को उच्च गुणवत्ता वाली JPG छवियों में बदलें।',
  'tool.jpgToPdf': 'JPG से PDF',
  'tool.jpgToPdfDesc': 'अपनी छवियों को PDF दस्तावेज़ में बदलें।',
  'tool.pdfToTxt': 'PDF से TXT',
  'tool.pdfToTxtDesc': 'PDF से टेक्स्ट निकालकर TXT फ़ाइल बनाएं।',
  'tool.pdfToWord': 'PDF से Word',
  'tool.pdfToWordDesc': 'PDF को संपादन योग्य Word दस्तावेज़ों में बदलें।',
  'tool.wordToPdf': 'Word से PDF',
  'tool.wordToPdfDesc': 'Word दस्तावेज़ों को PDF प्रारूप में बदलें।',
  'tool.pdfToPpt': 'PDF से PPT',
  'tool.pdfToPptDesc': 'अपने PDF को PowerPoint स्लाइड्स में बदलें।',
  'tool.pptToPdf': 'PPT से PDF',
  'tool.pptToPdfDesc': 'PowerPoint प्रस्तुतियों को PDF में बदलें।',
  'tool.pdfToExcel': 'PDF से Excel',
  'tool.pdfToExcelDesc': 'PDF तालिकाओं को Excel स्प्रेडशीट में निकालें।',
  'tool.excelToPdf': 'Excel से PDF',
  'tool.excelToPdfDesc': 'Excel स्प्रेडशीट को PDF प्रारूप में बदलें।',
  'tool.editPdf': 'PDF संपादित करें',
  'tool.editPdfDesc': 'अपने PDF में टेक्स्ट, इमेज और पृष्ठ संपादित करें।',
  'tool.signPdf': 'PDF पर हस्ताक्षर करें',
  'tool.signPdfDesc': 'किसी भी दस्तावेज़ पर अपना डिजिटल हस्ताक्षर जोड़ें।',
  'tool.repairPdf': 'PDF मरम्मत करें',
  'tool.repairPdfDesc': 'दूषित या क्षतिग्रस्त PDF फ़ाइलों को ठीक करें।',
  'tool.pdfToPdfa': 'PDF से PDF/A',
  'tool.pdfToPdfaDesc': 'PDF को संग्रहीय PDF/A प्रारूप में बदलें।',
  'tool.pdfMetadata': 'PDF मेटाडेटा',
  'tool.pdfMetadataDesc': 'PDF दस्तावेज़ गुण देखें और संपादित करें।',
  'tool.flattenPdf': 'PDF फ्लैट करें',
  'tool.flattenPdfDesc': 'फ़ॉर्म फ़ील्ड और एनोटेशन फ्लैट करें।',
  'tool.htmlToPdf': 'HTML से PDF',
  'tool.htmlToPdfDesc': 'वेब सामग्री को PDF दस्तावेज़ों में बदलें।',
  'tool.redactPdf': 'PDF रिडैक्ट करें',
  'tool.redactPdfDesc': 'संवेदनशील जानकारी को स्थायी रूप से हटाएं।',
  'tool.removeAnnotations': 'एनोटेशन हटाएं',
  'tool.removeAnnotationsDesc': 'टिप्पणियाँ और मार्कअप साफ़ करें।',
  'tool.removeWatermark': 'वॉटरमार्क हटाएं',
  'tool.removeWatermarkDesc': 'PDF दस्तावेज़ों से वॉटरमार्क हटाएं।',
  'tool.comparePdf': 'PDF तुलना करें',
  'tool.comparePdfDesc': 'दो PDF फ़ाइलों की तुलना करें।',
  'faq.header': 'अक्सर पूछे जाने वाले प्रश्न',
  'faq.q1': 'क्या Doczen मुफ्त है?',
  'faq.a1': 'हाँ! Doczen पूरी तरह से मुफ्त है। सभी PDF उपकरण बिना किसी छिपे शुल्क के उपलब्ध हैं।',
  'faq.q2': 'क्या मेरी फ़ाइलें सुरक्षित हैं?',
  'faq.a2': 'बिल्कुल। सभी फ़ाइलें अपलोड के दौरान एन्क्रिप्ट की जाती हैं और 24 घंटे बाद स्वचालित रूप से हटा दी जाती हैं। हम आपका डेटा कभी साझा नहीं करते।',
  'faq.q3': 'कौन से फ़ाइल आकार समर्थित हैं?',
  'faq.a3': 'आप प्रति दस्तावेज़ 50 MB तक की फ़ाइलें अपलोड कर सकते हैं।',
  'faq.q4': 'प्रसंस्करण में कितना समय लगता है?',
  'faq.a4': 'अधिकांश कार्य सेकंडों में पूरे हो जाते हैं। जटिल रूपांतरणों में थोड़ा अधिक समय लग सकता है।',
  'faq.q5': 'क्या कोई दैनिक सीमा है?',
  'faq.a5': 'पंजीकरण की आवश्यकता नहीं — मेहमान प्रति घंटे 10 फ़ाइलें प्रसंस्करण कर सकते हैं। उच्च सीमाओं के लिए मुफ्त खाता बनाएं।',
  'faq.q6': 'मेरे डेटा का क्या होता है?',
  'faq.a6': 'सभी अपलोड की गई फ़ाइलें 24 घंटे के भीतर स्वचालित रूप से हटा दी जाती हैं।',
  'cta.header': 'अपने PDF वर्कफ़्लो को सरल बनाने के लिए तैयार हैं?',
  'cta.desc': 'मुफ्त शुरू करें — कोई क्रेडिट कार्ड नहीं, कोई साइन अप नहीं।',
  'cta.start': 'उपकरणों का उपयोग शुरू करें',
  'cta.compress': 'PDF संपीड़ित करें',
  'footer.tagline': 'अपने PDF दस्तावेज़ों को ऑनलाइन संपादित, रूपांतरित और प्रबंधित करने का सबसे सरल तरीका। तेज़, सुरक्षित और मुफ्त।',
  'footer.quickLinks': 'त्वरित लिंक',
  'footer.moreTools': 'अधिक उपकरण',
  'footer.company': 'कंपनी',
  'footer.about': 'हमारे बारे में',
  'footer.privacy': 'गोपनीयता नीति',
  'footer.terms': 'सेवा की शर्तें',
  'footer.copyright': 'सर्वाधिकार सुरक्षित।',
  'footer.builtWith': 'PDF के लिए ❤️ से बनाया गया',
  'login.title': 'वापस स्वागत है',
  'login.subtitle': 'अपने Doczen खाते में साइन इन करें',
  'login.email': 'ईमेल पता',
  'login.emailPlaceholder': 'you@example.com',
  'login.password': 'पासवर्ड',
  'login.passwordPlaceholder': 'अपना पासवर्ड दर्ज करें',
  'login.signIn': 'साइन इन',
  'login.noAccount': 'खाता नहीं है?',
  'login.createOne': 'बनाएं',
  'register.title': 'खाता बनाएं',
  'register.subtitle': 'सेकंडों में Doczen का उपयोग शुरू करें',
  'register.name': 'पूरा नाम',
  'register.namePlaceholder': 'John Doe',
  'register.email': 'ईमेल पता',
  'register.emailPlaceholder': 'you@example.com',
  'register.password': 'पासवर्ड',
  'register.passwordPlaceholder': 'कम से कम 6 अक्षर',
  'register.confirmPassword': 'पासवर्ड की पुष्टि करें',
  'register.confirmPasswordPlaceholder': 'अपना पासवर्ड दोबारा दर्ज करें',
  'register.createAccount': 'खाता बनाएं',
  'register.hasAccount': 'पहले से खाता है?',
  'register.signIn': 'साइन इन करें',
  'dashboard.welcome': 'वापस स्वागत है',
  'dashboard.filesToday': 'आज की फ़ाइलें',
  'dashboard.quickActions': 'त्वरित कार्रवाई',
  'dashboard.recentActivity': 'हाल की गतिविधि',
  'dashboard.viewAll': 'सभी देखें',
  'dashboard.noActivity': 'अभी तक कोई गतिविधि नहीं। ऊपर दिए गए उपकरणों का उपयोग शुरू करें!',
  'dashboard.quick.mergePdf': 'PDF मर्ज करें',
  'dashboard.quick.splitPdf': 'PDF विभाजित करें',
  'dashboard.quick.compress': 'संपीड़ित करें',
  'dashboard.quick.rotate': 'घुमाएँ',
  'dashboard.quick.jpgToPdf': 'JPG से PDF',
  'dashboard.quick.editPdf': 'PDF संपादित करें',
  'history.title': 'इतिहास',
  'history.subtitle': 'अपने सभी पिछले PDF कार्यों को देखें।',
  'history.clearAll': 'सभी साफ़ करें',
  'history.clearing': 'साफ़ हो रहा है...',
  'history.confirmClear': 'क्या आप सभी इतिहास साफ़ करना चाहते हैं?',
  'history.noHistory': 'अभी तक कोई इतिहास नहीं।',
  'history.action': 'कार्रवाई',
  'history.file': 'फ़ाइल',
  'history.date': 'दिनांक',
  'history.status': 'स्थिति',
  'history.size': 'आकार',
  'history.previous': 'पिछला',
  'history.next': 'अगला',
  'upload.label': 'अपनी फ़ाइलें अपलोड करें',
  'upload.dragActive': 'अपलोड करने के लिए छोड़ें',
  'upload.filesSelected': 'फ़ाइलें चयनित — और ड्रॉप करें या बदलने के लिए क्लिक करें',
  'upload.dropActive': 'बढ़िया, यहाँ छोड़ें!',
  'upload.dragMultiple': '{maxFiles} फ़ाइलों तक यहाँ ड्रैग और ड्रॉप करें, या ब्राउज़ करने के लिए क्लिक करें',
  'upload.dragSingle': 'फ़ाइल यहाँ ड्रैग और ड्रॉप करें, या ब्राउज़ करने के लिए क्लिक करें',
  'upload.uploading': 'अपलोड हो रहा है...',
  'upload.error.invalidType': 'अमान्य फ़ाइल प्रकार। कृपया एक मान्य फ़ाइल अपलोड करें।',
  'upload.error.fileTooLarge': 'फ़ाइल बहुत बड़ी है। अधिकतम आकार 50MB है।',
  'upload.error.singleFile': 'एक समय में केवल एक फ़ाइल अपलोड की जा सकती है।',
  'result.action': 'आपकी फ़ाइल सफलतापूर्वक {action} हो गई।',
  'result.file': 'फ़ाइल',
  'result.size': 'आकार',
  'result.compression': 'संपीड़न',
  'result.original': 'मूल',
  'result.processAnother': 'दूसरी प्रक्रिया करें',
  'result.downloadAgain': 'फिर से डाउनलोड करें',
  'tool.uploadPdf': 'PDF अपलोड करें',
  'tool.uploadPdfs': 'PDF अपलोड करें',
  'tool.selectPdf': 'कृपया एक PDF फ़ाइल चुनें।',
  'tool.selectPdfs': 'मर्ज करने के लिए कम से कम 2 PDF फ़ाइलें चुनें।',
  'tool.mergePdf': 'PDF मर्ज करें',
  'tool.merging': 'PDF मर्ज हो रहे हैं...',
  'tool.splitPdf': 'PDF विभाजित करें',
  'tool.splitting': 'PDF विभाजित हो रहा है...',
  'tool.compressPdf': 'PDF संपीड़ित करें',
  'tool.compressing': 'PDF संपीड़ित हो रहा है...',
  'tool.setPassword': 'पासवर्ड सेट करें',
  'tool.password': 'पासवर्ड',
  'tool.confirmPassword': 'पासवर्ड की पुष्टि करें',
  'tool.qualitySettings': 'गुणवत्ता सेटिंग्स',
  'tool.compressionQuality': 'संपीड़न गुणवत्ता',
  'tool.lowSmaller': 'कम (छोटी फ़ाइल)',
  'tool.highBetter': 'उच्च (बेहतर गुणवत्ता)',
  'tool.rotationAngle': 'घूर्णन कोण',
  'tool.success': 'फ़ाइल सफलतापूर्वक रूपांतरित हुई। डाउनलोड स्वचालित रूप से शुरू हुआ।',
  'tool.downloadAgain': 'फिर से डाउनलोड करें',
  'tool.enterPassword': 'पासवर्ड दर्ज करें',
  'tool.enterPdfPassword': 'PDF पासवर्ड दर्ज करें',
  'login.error.required': 'कृपया सभी फ़ील्ड भरें।',
  'login.error.invalid': 'अमान्य ईमेल या पासवर्ड।',
  'register.error.required': 'कृपया सभी फ़ील्ड भरें।',
  'register.error.passwordLength': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए।',
  'register.error.passwordMatch': 'पासवर्ड मेल नहीं खाते।',
  'register.error.failed': 'पंजीकरण विफल रहा। कृपया पुनः प्रयास करें।',
  'tool.convertToPdf': 'PDF में बदलें',
  'tool.convertToWord': 'Word में बदलें',
  'tool.convertToJpg': 'JPG में बदलें',
  'tool.convertToPpt': 'PPT में बदलें',
  'tool.convertToExcel': 'Excel में बदलें',
  'tool.extractedText': 'निकाला गया टेक्स्ट',
  'tool.copyToClipboard': 'क्लिपबोर्ड पर कॉपी करें',
  'tool.content': 'सामग्री',
  'tool.enterHtml': 'HTML या सादा टेक्स्ट दर्ज करें',
  'tool.documentSettings': 'दस्तावेज़ सेटिंग्स',
  'tool.documentTitle': 'दस्तावेज़ शीर्षक',
  'tool.title': 'शीर्षक',
  'tool.author': 'लेखक',
  'tool.subject': 'विषय',
  'tool.keywords': 'कीवर्ड',
  'tool.readMetadata': 'मेटाडेटा पढ़ें',
  'tool.writeMetadata': 'मेटाडेटा लिखें',
  'tool.updateMetadata': 'मेटाडेटा अपडेट करें',
  'tool.pageCount': 'पृष्ठ संख्या',
  'tool.pageSizes': 'पृष्ठ आकार',
  'tool.options': 'विकल्प',
  'tool.mode': 'मोड',
  'tool.modeAuto': 'ऑटो',
  'tool.signPdf': 'PDF पर हस्ताक्षर करें',
  'tool.signatureText': 'हस्ताक्षर टेक्स्ट',
  'tool.rotatePdf': 'PDF घुमाएँ',
  'tool.rotating': 'PDF घूम रहा है...',
  'tool.protectPdf': 'PDF सुरक्षित करें',
  'tool.protecting': 'PDF सुरक्षित हो रहा है...',
  'tool.unlockPdf': 'PDF अनलॉक करें',
  'tool.unlocking': 'PDF अनलॉक हो रहा है...',
  'tool.repairPdf': 'PDF मरम्मत करें',
  'tool.repairing': 'PDF की मरम्मत हो रही है...',
  'tool.flattenPdf': 'PDF फ्लैट करें',
  'tool.flattening': 'PDF फ्लैट हो रहा है...',
  'tool.redactPdf': 'PDF रिडैक्ट करें',
  'tool.redacting': 'PDF रिडैक्ट हो रहा है...',
  'tool.removeAnnotations': 'एनोटेशन हटाएं',
  'tool.removingAnnotations': 'एनोटेशन हटाए जा रहे हैं...',
  'tool.removeWatermark': 'वॉटरमार्क हटाएं',
  'tool.removingWatermark': 'वॉटरमार्क हटाया जा रहा है...',
  'tool.comparePdf': 'PDF तुलना करें',
  'tool.comparing': 'PDF तुलना हो रही है...',
  'tool.mergeDesc': 'एकाधिक PDF फ़ाइलों को एक दस्तावेज़ में मर्ज करें',
  'tool.splitDesc': 'PDF से अलग-अलग पृष्ठ निकालें',
  'tool.compressDesc': 'गुणवत्ता खोए बिना PDF का आकार कम करें',
  'tool.rotateDesc': 'पृष्ठों को किसी भी कोण पर घुमाएं',
  'tool.protectDesc': 'अपने PDF दस्तावेज़ों में पासवर्ड सुरक्षा जोड़ें',
  'tool.unlockDesc': 'अपने PDF दस्तावेज़ों से पासवर्ड सुरक्षा हटाएं',
  'tool.editDesc': 'अपने PDF दस्तावेज़ों में एनोटेशन और टेक्स्ट जोड़ें।',
  'tool.repairDesc2': 'दूषित PDF फ़ाइलों को ठीक करें',
  'tool.pdfToPdfaDesc2': 'लंबे समय तक संग्रहण के लिए PDF को PDF/A प्रारूप में बदलें',
  'tool.metadataDesc': 'PDF दस्तावेज़ गुण देखें और संपादित करें',
  'tool.flattenDesc2': 'अपने PDF में फ़ॉर्म फ़ील्ड और एनोटेशन फ्लैट करें',
  'tool.htmlToPdfDesc2': 'HTML और टेक्स्ट सामग्री को PDF दस्तावेज़ में बदलें',
  'tool.redactDesc2': 'अपने PDF से संवेदनशील जानकारी स्थायी रूप से हटाएं',
  'tool.compareDesc': 'दो PDF फ़ाइलों की तुलना करें और अंतर खोजें',
  'tool.convertError': 'रूपांतरण विफल रहा। कृपया पुनः प्रयास करें।',
  'tool.genericError': 'कुछ गलत हो गया।',
  'tool.toast.merged': 'PDF सफलतापूर्वक मर्ज हो गए!',
  'tool.toast.compressed': 'PDF सफलतापूर्वक संपीड़ित हुआ!',
  'tool.selectPdfRotate': 'कृपया घुमाने के लिए एक PDF फ़ाइल चुनें।',
  'tool.selectPdfProtect': 'कृपया सुरक्षित करने के लिए एक PDF फ़ाइल चुनें।',
  'tool.passwordMinLength': 'पासवर्ड कम से कम 4 अक्षर का होना चाहिए।',
  'tool.passwordDoNotMatch': 'पासवर्ड मेल नहीं खाते।',
  'tool.enterPdfPasswordError': 'कृपया PDF पासवर्ड दर्ज करें।',
  'tool.enterWatermarkTextError': 'कृपया वॉटरमार्क टेक्स्ट दर्ज करें।',
  'tool.enterPageOrderError': 'कृपया वांछित पृष्ठ क्रम दर्ज करें।',
  'tool.enterValidPageNumbers': 'कृपया मान्य पृष्ठ संख्याएं दर्ज करें (अल्पविराम से अलग की गई धनात्मक पूर्णांक)।',
  'tool.enterPagesToDeleteError': 'कृपया हटाने के लिए पृष्ठ दर्ज करें।',
  'tool.enterAtLeastOneTerm': 'कृपया रिडैक्ट करने के लिए कम से कम एक शब्द दर्ज करें।',
  'tool.enterContentToConvert': 'कृपया रूपांतरण के लिए HTML या टेक्स्ट सामग्री दर्ज करें।',
  'tool.pageNumberSettings': 'पृष्ठ संख्या सेटिंग्स',
  'tool.startNumber': 'प्रारंभ संख्या',
  'tool.fontSize': 'फ़ॉन्ट आकार',
  'tool.position': 'स्थिति',
  'tool.bottomCenter': 'नीचे केंद्र',
  'tool.topCenter': 'ऊपर केंद्र',
  'tool.watermarkText': 'वॉटरमार्क टेक्स्ट',
  'tool.pageOrder': 'पृष्ठ क्रम',
  'tool.pagesToDelete': 'हटाने के लिए पृष्ठ',
  'tool.termsToRedact': 'रिडैक्ट करने के लिए शब्द',
  'tool.firstPdf': 'पहली PDF',
  'tool.secondPdf': 'दूसरी PDF',
  'tool.comparisonResults': 'तुलना परिणाम',
  'tool.compareAnother': 'दूसरी तुलना करें',
});

addTranslations('es', {
  'nav.home': 'Inicio',
  'nav.about': 'Acerca de',
  'nav.allTools': 'Todas las herramientas',
  'nav.tools.merge': 'Unir PDF',
  'nav.tools.split': 'Dividir PDF',
  'nav.tools.compress': 'Comprimir PDF',
  'nav.tools.rotate': 'Rotar PDF',
  'nav.tools.protect': 'Proteger PDF',
  'nav.tools.unlock': 'Desbloquear PDF',
  'nav.tools.addPageNumbers': 'Añadir números de página',
  'nav.tools.addWatermark': 'Añadir marca de agua',
  'nav.tools.extractText': 'Extraer texto',
  'nav.tools.reorderPages': 'Reordenar páginas',
  'nav.tools.deletePages': 'Eliminar páginas',
  'nav.tools.pdfToJpg': 'PDF a JPG',
  'nav.tools.jpgToPdf': 'JPG a PDF',
  'nav.tools.pdfToTxt': 'PDF a TXT',
  'nav.tools.pdfToWord': 'PDF a Word',
  'nav.tools.wordToPdf': 'Word a PDF',
  'nav.tools.pdfToPpt': 'PDF a PPT',
  'nav.tools.pptToPdf': 'PPT a PDF',
  'nav.tools.pdfToExcel': 'PDF a Excel',
  'nav.tools.excelToPdf': 'Excel a PDF',
  'nav.tools.editPdf': 'Editar PDF',
  'nav.tools.signPdf': 'Firmar PDF',
  'nav.dashboard': 'Panel',
  'nav.history': 'Historial',
  'nav.logout': 'Cerrar sesión',
  'nav.login': 'Iniciar sesión',
  'nav.register': 'Registrarse',
  'nav.language': 'Idioma',
  'hero.title1': 'Tus PDF,',
  'hero.title2': 'Perfeccionados.',
  'hero.tryMerge': 'Probar Unir PDF',
  'hero.allTools': 'Todas las herramientas',
  'tools.header': 'Todo lo que necesitas',
  'tool.mergePdf': 'Unir PDF',
  'tool.mergePdfDesc': 'Combina múltiples PDF en un solo archivo al instante.',
  'tool.splitPdf': 'Dividir PDF',
  'tool.splitPdfDesc': 'Divide un PDF en documentos separados por páginas.',
  'tool.compressPdf': 'Comprimir PDF',
  'tool.compressPdfDesc': 'Reduce el tamaño del archivo PDF sin pérdida de calidad.',
  'tool.rotatePdf': 'Rotar PDF',
  'tool.rotatePdfDesc': 'Rota las páginas de tu PDF a cualquier ángulo.',
  'tool.protectPdf': 'Proteger PDF',
  'tool.protectPdfDesc': 'Añade una contraseña para asegurar tus archivos PDF.',
  'tool.unlockPdf': 'Desbloquear PDF',
  'tool.unlockPdfDesc': 'Elimina la protección por contraseña de los PDF.',
  'faq.header': 'Preguntas frecuentes',
  'faq.q1': '¿Doczen es gratis?',
  'faq.a1': '¡Sí! Doczen es completamente gratuito.',
  'cta.header': '¿Listo para simplificar tu flujo de trabajo con PDF?',
  'cta.desc': 'Comienza gratis — sin tarjeta de crédito, sin registro.',
  'cta.start': 'Comenzar a usar herramientas',
  'footer.tagline': 'La forma más sencilla de editar, convertir y gestionar tus documentos PDF en línea.',
  'footer.quickLinks': 'Enlaces rápidos',
  'footer.moreTools': 'Más herramientas',
  'footer.company': 'Empresa',
  'footer.about': 'Acerca de',
  'footer.privacy': 'Política de privacidad',
  'footer.terms': 'Términos del servicio',
  'login.title': 'Bienvenido de nuevo',
  'login.subtitle': 'Inicia sesión en tu cuenta de Doczen',
  'login.email': 'Correo electrónico',
  'login.password': 'Contraseña',
  'login.signIn': 'Iniciar sesión',
  'login.noAccount': '¿No tienes una cuenta?',
  'login.createOne': 'Crear una',
  'register.title': 'Crea tu cuenta',
  'register.subtitle': 'Comienza a usar Doczen en segundos',
  'register.name': 'Nombre completo',
  'register.email': 'Correo electrónico',
  'register.password': 'Contraseña',
  'register.confirmPassword': 'Confirmar contraseña',
  'register.createAccount': 'Crear cuenta',
  'register.hasAccount': '¿Ya tienes una cuenta?',
  'register.signIn': 'Iniciar sesión',
  'dashboard.welcome': 'Bienvenido de nuevo',
  'dashboard.filesToday': 'Archivos hoy',
  'dashboard.quickActions': 'Acciones rápidas',
  'dashboard.recentActivity': 'Actividad reciente',
  'dashboard.viewAll': 'Ver todo',
  'history.title': 'Historial',
  'history.clearAll': 'Limpiar todo',
  'history.noHistory': 'Aún no hay historial.',
  'history.action': 'Acción',
  'history.file': 'Archivo',
  'history.date': 'Fecha',
  'history.status': 'Estado',
  'history.size': 'Tamaño',
  'history.previous': 'Anterior',
  'history.next': 'Siguiente',
  'tool.uploadPdf': 'Subir PDF',
  'tool.selectPdf': 'Por favor selecciona un archivo PDF.',
  'tool.mergePdf': 'Unir PDF',
  'tool.merging': 'Uniendo PDF...',
  'tool.success': 'Archivo convertido exitosamente.',
  'tool.downloadAgain': 'Descargar de nuevo',
  'tool.convertToPdf': 'Convertir a PDF',
});

addTranslations('fr', {
  'nav.home': 'Accueil',
  'nav.about': 'À propos',
  'nav.allTools': 'Tous les outils',
  'nav.tools.merge': 'Fusionner PDF',
  'nav.tools.split': 'Diviser PDF',
  'nav.tools.compress': 'Compresser PDF',
  'nav.tools.rotate': 'Pivoter PDF',
  'nav.tools.protect': 'Protéger PDF',
  'nav.tools.unlock': 'Déverrouiller PDF',
  'nav.tools.editPdf': 'Modifier PDF',
  'nav.tools.signPdf': 'Signer PDF',
  'nav.tools.pdfToWord': 'PDF vers Word',
  'nav.tools.wordToPdf': 'Word vers PDF',
  'nav.tools.pdfToJpg': 'PDF vers JPG',
  'nav.tools.jpgToPdf': 'JPG vers PDF',
  'nav.dashboard': 'Tableau de bord',
  'nav.history': 'Historique',
  'nav.logout': 'Déconnexion',
  'nav.login': 'Connexion',
  'nav.register': 'S\'inscrire',
  'nav.language': 'Langue',
  'hero.title1': 'Vos PDF,',
  'hero.title2': 'Parfaits.',
  'hero.tryMerge': 'Essayer Fusionner PDF',
  'hero.allTools': 'Tous les outils',
  'tools.header': 'Tout ce dont vous avez besoin',
  'footer.quickLinks': 'Liens rapides',
  'footer.company': 'Société',
  'footer.about': 'À propos',
  'footer.privacy': 'Politique de confidentialité',
  'footer.terms': 'Conditions d\'utilisation',
  'login.title': 'Bon retour',
  'login.email': 'Adresse e-mail',
  'login.password': 'Mot de passe',
  'login.signIn': 'Se connecter',
  'register.title': 'Créez votre compte',
  'register.name': 'Nom complet',
  'register.email': 'Adresse e-mail',
  'register.password': 'Mot de passe',
  'register.createAccount': 'Créer un compte',
  'dashboard.filesToday': 'Fichiers aujourd\'hui',
  'dashboard.quickActions': 'Actions rapides',
  'history.title': 'Historique',
  'history.clearAll': 'Tout effacer',
  'tool.uploadPdf': 'Télécharger PDF',
  'tool.mergePdf': 'Fusionner PDF',
  'tool.success': 'Fichier converti avec succès.',
});

addTranslations('ar', {
  'nav.home': 'الرئيسية',
  'nav.about': 'حول',
  'nav.allTools': 'جميع الأدوات',
  'nav.tools.merge': 'دمج PDF',
  'nav.tools.split': 'تقسيم PDF',
  'nav.tools.compress': 'ضغط PDF',
  'nav.tools.rotate': 'تدوير PDF',
  'nav.tools.protect': 'حماية PDF',
  'nav.tools.unlock': 'فتح PDF',
  'nav.tools.editPdf': 'تعديل PDF',
  'nav.tools.signPdf': 'توقيع PDF',
  'nav.dashboard': 'لوحة التحكم',
  'nav.history': 'السجل',
  'nav.logout': 'تسجيل الخروج',
  'nav.login': 'تسجيل الدخول',
  'nav.register': 'التسجيل',
  'nav.language': 'اللغة',
  'hero.title1': 'ملفات PDF الخاصة بك،',
  'hero.title2': 'مثالية.',
  'hero.tryMerge': 'جرب دمج PDF',
  'hero.allTools': 'جميع الأدوات',
  'tools.header': 'كل ما تحتاجه',
  'footer.quickLinks': 'روابط سريعة',
  'footer.company': 'الشركة',
  'footer.about': 'حول',
  'footer.privacy': 'سياسة الخصوصية',
  'footer.terms': 'شروط الخدمة',
  'login.title': 'مرحباً بعودتك',
  'login.email': 'البريد الإلكتروني',
  'login.password': 'كلمة المرور',
  'login.signIn': 'تسجيل الدخول',
  'register.title': 'إنشاء حسابك',
  'register.name': 'الاسم الكامل',
  'register.email': 'البريد الإلكتروني',
  'register.password': 'كلمة المرور',
  'register.createAccount': 'إنشاء حساب',
  'dashboard.filesToday': 'الملفات اليوم',
  'dashboard.quickActions': 'إجراءات سريعة',
  'history.title': 'السجل',
  'tool.uploadPdf': 'رفع PDF',
  'tool.mergePdf': 'دمج PDF',
});

addTranslations('bn', {
  'nav.home': 'হোম',
  'nav.about': 'আমাদের সম্পর্কে',
  'nav.allTools': 'সব টুল',
  'nav.tools.merge': 'PDF মার্জ করুন',
  'nav.tools.split': 'PDF বিভক্ত করুন',
  'nav.tools.compress': 'PDF কম্প্রেস করুন',
  'nav.tools.rotate': 'PDF ঘোরান',
  'nav.tools.protect': 'PDF সুরক্ষিত করুন',
  'nav.tools.unlock': 'PDF আনলক করুন',
  'nav.tools.editPdf': 'PDF সম্পাদনা করুন',
  'nav.tools.signPdf': 'PDF সই করুন',
  'nav.dashboard': 'ড্যাশবোর্ড',
  'nav.history': 'ইতিহাস',
  'nav.logout': 'লগ আউট',
  'nav.login': 'লগ ইন',
  'nav.register': 'নিবন্ধন',
  'nav.language': 'ভাষা',
  'hero.title1': 'আপনার PDF,',
  'hero.title2': 'নিখুঁত।',
  'hero.tryMerge': 'মার্জ PDF试试',
  'hero.allTools': 'সব টুল',
  'tools.header': 'আপনার প্রয়োজনীয় সবকিছু',
  'footer.quickLinks': 'দ্রুত লিংক',
  'footer.company': 'কোম্পানি',
  'footer.about': 'আমাদের সম্পর্কে',
  'footer.privacy': 'গোপনীয়তা নীতি',
  'footer.terms': 'সেবার শর্তাবলী',
  'login.title': 'ফিরে আসায় স্বাগতম',
  'login.email': 'ইমেইল ঠিকানা',
  'login.password': 'পাসওয়ার্ড',
  'login.signIn': 'সাইন ইন',
  'register.title': 'আপনার অ্যাকাউন্ট তৈরি করুন',
  'register.name': 'পূর্ণ নাম',
  'register.email': 'ইমেইল ঠিকানা',
  'register.password': 'পাসওয়ার্ড',
  'register.createAccount': 'অ্যাকাউন্ট তৈরি করুন',
  'dashboard.filesToday': 'আজকের ফাইল',
  'dashboard.quickActions': 'দ্রুত কর্ম',
  'history.title': 'ইতিহাস',
  'tool.uploadPdf': 'PDF আপলোড করুন',
  'tool.mergePdf': 'PDF মার্জ করুন',
});

const LANGUAGE_MAP = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', native: '简体中文' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', native: '繁體中文' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe' },
  { code: 'pl', name: 'Polish', native: 'Polski' },
  { code: 'sv', name: 'Swedish', native: 'Svenska' },
  { code: 'da', name: 'Danish', native: 'Dansk' },
  { code: 'no', name: 'Norwegian', native: 'Norsk' },
  { code: 'fi', name: 'Finnish', native: 'Suomi' },
  { code: 'cs', name: 'Czech', native: 'Čeština' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar' },
  { code: 'ro', name: 'Romanian', native: 'Română' },
  { code: 'bg', name: 'Bulgarian', native: 'Български' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά' },
  { code: 'th', name: 'Thai', native: 'ไทย' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська' },
  { code: 'he', name: 'Hebrew', native: 'עברית' },
  { code: 'ca', name: 'Catalan', native: 'Català' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski' },
  { code: 'sr', name: 'Serbian', native: 'Српски' },
  { code: 'sl', name: 'Slovenian', native: 'Slovenščina' },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuvių' },
  { code: 'lv', name: 'Latvian', native: 'Latviešu' },
  { code: 'et', name: 'Estonian', native: 'Eesti' },
  { code: 'is', name: 'Icelandic', native: 'Íslenska' },
  { code: 'eu', name: 'Basque', native: 'Euskara' },
  { code: 'gl', name: 'Galician', native: 'Galego' },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg' },
  { code: 'fil', name: 'Filipino', native: 'Filipino' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'fa', name: 'Persian', native: 'فارسی' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली' },
  { code: 'my', name: 'Burmese', native: 'မြန်မာဘာသာ' },
];

const STORAGE_KEY = 'doczen_language';

function getInitialLanguage() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved && LANGUAGE_MAP.some(l => l.code === saved)) return saved;
    const browserLang = navigator.language?.split('-')[0] || 'en';
    if (LANGUAGE_MAP.some(l => l.code === browserLang)) return browserLang;
  } catch {}
  return 'en';
}

const TranslationContext = createContext(null);

export function useLanguage() {
  const ctx = useContext(TranslationContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(getInitialLanguage);

  const setLanguage = useCallback((code) => {
    if (LANGUAGE_MAP.some(l => l.code === code)) {
      setLangState(code);
      try { localStorage.setItem(STORAGE_KEY, code); } catch {}
    }
  }, []);

  const currentLang = LANGUAGE_MAP.find(l => l.code === lang) || LANGUAGE_MAP[0];

  const t = useCallback((key, fallback, vars) => {
    const langTranslations = TRANSLATIONS[lang];
    let text = langTranslations && langTranslations[key];
    if (text === undefined) {
      text = TRANSLATIONS['en'][key];
    }
    if (text === undefined) {
      text = fallback || key;
    }
    if (vars) {
      Object.keys(vars).forEach(k => {
        text = text.replace(`{${k}}`, vars[k]);
      });
    }
    return text;
  }, [lang]);

  const dir = ['ar', 'he', 'fa', 'ur'].includes(lang) ? 'rtl' : 'ltr';

  return (
    <TranslationContext.Provider value={{ lang, setLanguage, currentLang, t, dir, LANGUAGE_MAP }}>
      <div dir={dir} lang={lang}>
        {children}
      </div>
    </TranslationContext.Provider>
  );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <BrowserRouter>
      <LanguageProvider>
        <App />
      </LanguageProvider>
    </BrowserRouter>
  </React.StrictMode>
);
