import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

Future<void> configureInjection() async {
  // Manual configuration for now
  // In a real app, this would be generated by injectable_generator
}

// This is a placeholder for the generated config
// Run `flutter packages pub run build_runner build` to generate the actual config
